<?php
/**
 * Do not edit this file.
 */

if ( version_compare( phpversion(), '7.0', '<' ) ) {
	die( 'Execution aborted because PHP Version is lower than 7.0' );
}

require_once dirname( __DIR__ ) . '/vendor/autoload.php';

define( 'WP_CORE_DIRNAME', 'core' );

Leaves_And_Love\WP_Composer_Stack\Config::instance()->run();

$table_prefix = DB_PREFIX;

require_once ABSPATH . 'wp-settings.php';
